import streamlit as st

def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return bmi

def calculate_calories(age, weight, height, activity_level, gender):
    if gender == "Male":
        bmr = 88.36 + (13.4 * weight) + (4.8 * height * 100) - (5.7 * age)
    else:
        bmr = 447.6 + (9.2 * weight) + (3.1 * height * 100) - (4.3 * age)
    
    activity_multipliers = {
        "Sedentary": 1.2,
        "Lightly Active": 1.375,
        "Moderately Active": 1.55,
        "Very Active": 1.725,
        "Super Active": 1.9
    }
    
    return bmr * activity_multipliers[activity_level]

def calculate_water_intake(weight):
    return weight * 0.033  # Recommended daily water intake in liters

# Streamlit UI
st.title("💪 Health & Fitness Tracker")

st.sidebar.header("User Information")
name = st.sidebar.text_input("Enter your name:")
age = st.sidebar.number_input("Age", min_value=10, max_value=100, value=25)
weight = st.sidebar.number_input("Weight (kg)", min_value=30, max_value=200, value=70)
height = st.sidebar.number_input("Height (m)", min_value=1.0, max_value=2.5, value=1.75)
gender = st.sidebar.selectbox("Gender", ["Male", "Female"])
activity_level = st.sidebar.selectbox("Activity Level", 
                                      ["Sedentary", "Lightly Active", "Moderately Active", "Very Active", "Super Active"])

if st.sidebar.button("Calculate"):
    bmi = calculate_bmi(weight, height)
    calorie_needs = calculate_calories(age, weight, height, activity_level, gender)
    water_needs = calculate_water_intake(weight)

    st.subheader(f"👤 {name}'s Health Summary")
    
    st.write(f"💡 **BMI**: {bmi:.2f}")
    if bmi < 18.5:
        st.write("🔵 Underweight")
    elif 18.5 <= bmi < 24.9:
        st.write("🟢 Normal weight")
    elif 25 <= bmi < 29.9:
        st.write("🟠 Overweight")
    else:
        st.write("🔴 Obese")

    st.write(f"🔥 **Daily Calorie Requirement**: {calorie_needs:.2f} kcal")
    st.write(f"💧 **Recommended Daily Water Intake**: {water_needs:.2f} liters")

st.markdown("---")
st.markdown("📌 *Track your health & stay fit!* 🚀")
